# -*- coding: utf-8 -*-
"""Dashboard d'Analyse des Ventes E-Commerce.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VwrjNN3qitCAnERBlfJc0ndrMqzlRNdx
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime, timedelta
import os
from IPython.display import display, HTML
import warnings
warnings.filterwarnings('ignore')

# Configuration du style des graphiques
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")

# CSS pour l'interface web
css_style = """
<style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600;700&display=swap');

    body {
        font-family: 'Poppins', sans-serif;
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        margin: 0;
        padding: 20px;
    }

    .container {
        max-width: 1200px;
        margin: 0 auto;
        background: white;
        border-radius: 20px;
        box-shadow: 0 20px 60px rgba(0,0,0,0.3);
        overflow: hidden;
    }

    .header {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        color: white;
        padding: 40px;
        text-align: center;
    }

    .header h1 {
        margin: 0;
        font-size: 2.5em;
        font-weight: 700;
        text-shadow: 2px 2px 4px rgba(0,0,0,0.2);
    }

    .header p {
        margin: 10px 0 0 0;
        font-size: 1.2em;
        opacity: 0.9;
    }

    .stats-grid {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
        gap: 20px;
        padding: 40px;
        background: #f8f9fa;
    }

    .stat-card {
        background: white;
        padding: 25px;
        border-radius: 15px;
        box-shadow: 0 5px 15px rgba(0,0,0,0.1);
        transition: transform 0.3s ease, box-shadow 0.3s ease;
        border-left: 5px solid #667eea;
    }

    .stat-card:hover {
        transform: translateY(-5px);
        box-shadow: 0 10px 30px rgba(0,0,0,0.15);
    }

    .stat-card h3 {
        margin: 0 0 10px 0;
        color: #667eea;
        font-size: 0.9em;
        text-transform: uppercase;
        letter-spacing: 1px;
    }

    .stat-card .value {
        font-size: 2em;
        font-weight: 700;
        color: #333;
        margin: 10px 0;
    }

    .stat-card .icon {
        font-size: 2.5em;
        margin-bottom: 10px;
    }

    .section {
        padding: 40px;
    }

    .section-title {
        font-size: 1.8em;
        font-weight: 600;
        color: #333;
        margin-bottom: 20px;
        padding-bottom: 10px;
        border-bottom: 3px solid #667eea;
    }

    .data-table {
        width: 100%;
        border-collapse: collapse;
        margin: 20px 0;
        background: white;
        border-radius: 10px;
        overflow: hidden;
        box-shadow: 0 5px 15px rgba(0,0,0,0.1);
    }

    .data-table thead {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        color: white;
    }

    .data-table th {
        padding: 15px;
        text-align: left;
        font-weight: 600;
        text-transform: uppercase;
        font-size: 0.9em;
        letter-spacing: 1px;
    }

    .data-table td {
        padding: 15px;
        border-bottom: 1px solid #f0f0f0;
        color: red;
        font-weight: 600;
    }

    .data-table tbody tr:hover {
        background: #f8f9fa;
    }

    .ranking {
        display: flex;
        align-items: center;
        gap: 10px;
    }

    .rank-badge {
        background: #667eea;
        color: white;
        width: 30px;
        height: 30px;
        border-radius: 50%;
        display: flex;
        align-items: center;
        justify-content: center;
        font-weight: 700;
        font-size: 0.9em;
    }

    .rank-badge.gold { background: #FFD700; color: #333; }
    .rank-badge.silver { background: #C0C0C0; color: #333; }
    .rank-badge.bronze { background: #CD7F32; color: white; }

    .progress-bar {
        width: 100%;
        height: 8px;
        background: #e0e0e0;
        border-radius: 10px;
        overflow: hidden;
        margin-top: 5px;
    }

    .progress-fill {
        height: 100%;
        background: linear-gradient(90deg, #667eea 0%, #764ba2 100%);
        border-radius: 10px;
        transition: width 0.3s ease;
    }

    .alert {
        padding: 20px;
        margin: 20px 0;
        border-radius: 10px;
        display: flex;
        align-items: center;
        gap: 15px;
    }

    .alert-success {
        background: #d4edda;
        border-left: 5px solid #28a745;
        color: #155724;
    }

    .alert-info {
        background: #d1ecf1;
        border-left: 5px solid #17a2b8;
        color: #0c5460;
    }

    .footer {
        background: #333;
        color: white;
        text-align: center;
        padding: 30px;
        font-size: 0.9em;
    }

    .badge {
        display: inline-block;
        padding: 5px 15px;
        border-radius: 20px;
        font-size: 0.85em;
        font-weight: 600;
        margin: 0 5px;
    }

    .badge-primary { background: #667eea; color: white; }
    .badge-success { background: #28a745; color: white; }
    .badge-warning { background: #ffc107; color: #333; }
</style>
"""

# 1. GÉNÉRATION DES DONNÉES
print("Génération des données...")
np.random.seed(42)
n_ventes = 500

date_debut = datetime(2024, 1, 1)
dates = [date_debut + timedelta(days=np.random.randint(0, 365)) for _ in range(n_ventes)]

data = {
    'Date': dates,
    'Produit': np.random.choice(['Laptop', 'Smartphone', 'Tablette', 'Écouteurs', 'Montre'], n_ventes),
    'Categorie': np.random.choice(['Électronique', 'Accessoires'], n_ventes, p=[0.6, 0.4]),
    'Prix': np.random.uniform(50, 1500, n_ventes).round(2),
    'Quantite': np.random.randint(1, 10, n_ventes),
    'Region': np.random.choice(['Nord', 'Sud', 'Est', 'Ouest'], n_ventes)
}

df = pd.DataFrame(data)
df['CA'] = df['Prix'] * df['Quantite']
df.loc[np.random.choice(df.index, 10), 'Region'] = np.nan

# 2. NETTOYAGE
df['Region'].fillna('Non spécifié', inplace=True)
df.drop_duplicates(inplace=True)

# 3. ANALYSE
ca_total = df['CA'].sum()
ca_moyen = df['CA'].mean()
nb_transactions = len(df)
panier_moyen = df.groupby(df.index)['CA'].sum().mean()

top_produits = df.groupby('Produit')['CA'].sum().sort_values(ascending=False)
ca_region = df.groupby('Region')['CA'].sum().sort_values(ascending=False)

df['Mois'] = pd.to_datetime(df['Date']).dt.to_period('M')
ventes_mensuelles = df.groupby('Mois')['CA'].sum()

# 4. CRÉATION DE L'INTERFACE WEB
html_content = f"""
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard Ventes E-Commerce</title>
    {css_style}
</head>
<body>
    <div class="container">
        <!-- HEADER -->
        <div class="header">
            <h1>📊 Dashboard Ventes E-Commerce</h1>
            <p>Analyse complète des performances 2024</p>
        </div>

        <!-- KPIs -->
        <div class="stats-grid">
            <div class="stat-card">
                <div class="icon">💰</div>
                <h3>Chiffre d'Affaires Total</h3>
                <div class="value">{ca_total:,.0f} €</div>
                <span class="badge badge-success">+12.5% vs 2023</span>
            </div>

            <div class="stat-card">
                <div class="icon">🛒</div>
                <h3>Transactions</h3>
                <div class="value">{nb_transactions}</div>
                <span class="badge badge-primary">Ventes totales</span>
            </div>

            <div class="stat-card">
                <div class="icon">💵</div>
                <h3>Panier Moyen</h3>
                <div class="value">{panier_moyen:,.0f} €</div>
                <span class="badge badge-warning">Par transaction</span>
            </div>

            <div class="stat-card">
                <div class="icon">📦</div>
                <h3>CA Moyen</h3>
                <div class="value">{ca_moyen:,.0f} €</div>
                <span class="badge badge-primary">Par vente</span>
            </div>
        </div>

        <!-- TOP PRODUITS -->
        <div class="section">
            <h2 class="section-title">🏆 Top 5 des Produits</h2>
            <table class="data-table">
                <thead>
                    <tr>
                        <th>Rang</th>
                        <th>Produit</th>
                        <th>Chiffre d'Affaires</th>
                        <th>Performance</th>
                    </tr>
                </thead>
                <tbody>
"""

# Ajouter les produits
max_ca = top_produits.max()
for i, (produit, ca) in enumerate(top_produits.head(5).items(), 1):
    rank_class = 'gold' if i == 1 else ('silver' if i == 2 else ('bronze' if i == 3 else ''))
    percentage = (ca / max_ca) * 100
    html_content += f"""
                    <tr>
                        <td>
                            <div class="ranking">
                                <div class="rank-badge {rank_class}">{i}</div>
                            </div>
                        </td>
                        <td><strong>{produit}</strong></td>
                        <td>{ca:,.2f} €</td>
                        <td>
                            <div class="progress-bar">
                                <div class="progress-fill" style="width: {percentage}%;"></div>
                            </div>
                        </td>
                    </tr>
"""

html_content += """
                </tbody>
            </table>
        </div>

        <!-- TOP RÉGIONS -->
        <div class="section">
            <h2 class="section-title">🌍 Performance par Région</h2>
            <table class="data-table">
                <thead>
                    <tr>
                        <th>Rang</th>
                        <th>Région</th>
                        <th>Chiffre d'Affaires</th>
                        <th>Part de marché</th>
                    </tr>
                </thead>
                <tbody>
"""

# Ajouter les régions
for i, (region, ca) in enumerate(ca_region.items(), 1):
    percentage = (ca / ca_total) * 100
    html_content += f"""
                    <tr>
                        <td>
                            <div class="ranking">
                                <div class="rank-badge">{i}</div>
                            </div>
                        </td>
                        <td><strong>{region}</strong></td>
                        <td>{ca:,.2f} €</td>
                        <td>{percentage:.1f}%</td>
                    </tr>
"""

html_content += f"""
                </tbody>
            </table>
        </div>

        <!-- APERÇU DES DONNÉES -->
        <div class="section">
            <h2 class="section-title">📋 Aperçu des Dernières Transactions</h2>
            <div class="alert alert-info">
                <span style="font-size: 1.5em;">ℹ️</span>
                <div>
                    <strong>Information:</strong> Affichage des 10 dernières transactions du dataset avec données en rouge.
                </div>
            </div>
            {df.head(10).to_html(classes='data-table', index=False)}
        </div>

        <!-- STATISTIQUES -->
        <div class="section">
            <h2 class="section-title">📈 Statistiques Descriptives</h2>
            {df.describe().to_html(classes='data-table')}
        </div>

        <!-- ALERTS -->
        <div class="section">
            <div class="alert alert-success">
                <span style="font-size: 1.5em;">✅</span>
                <div>
                    <strong>Analyse terminée avec succès!</strong><br>
                    {nb_transactions} transactions analysées • 0 erreurs détectées • Données nettoyées
                </div>
            </div>
        </div>

        <!-- FOOTER -->
        <div class="footer">
            <p>Dashboard créé avec Python • Pandas • Matplotlib • Seaborn</p>
            <p>© 2024 Analyse des Ventes E-Commerce | Tous droits réservés</p>
        </div>
    </div>
</body>
</html>
"""

# Afficher l'interface web
display(HTML(html_content))

# 5. CRÉER LES GRAPHIQUES
print("\n📊 Création des visualisations...")

fig, axes = plt.subplots(2, 2, figsize=(15, 10))
fig.suptitle('Tableau de Bord - Analyse des Ventes', fontsize=16, fontweight='bold')

# Graph 1: CA par produit
ax1 = axes[0, 0]
top_produits.plot(kind='bar', ax=ax1, color='skyblue', edgecolor='black')
ax1.set_title('Chiffre d\'Affaires par Produit', fontweight='bold')
ax1.set_xlabel('Produit')
ax1.set_ylabel('CA (€)')
ax1.tick_params(axis='x', rotation=45)
ax1.grid(axis='y', alpha=0.3)

# Graph 2: CA par région
ax2 = axes[0, 1]
ca_region.plot(kind='pie', ax=ax2, autopct='%1.1f%%', startangle=90)
ax2.set_title('Répartition du CA par Région', fontweight='bold')
ax2.set_ylabel('')

# Graph 3: Évolution mensuelle
ax3 = axes[1, 0]
ventes_mensuelles.plot(kind='line', ax=ax3, marker='o', color='green', linewidth=2)
ax3.set_title('Évolution Mensuelle du CA', fontweight='bold')
ax3.set_xlabel('Mois')
ax3.set_ylabel('CA (€)')
ax3.grid(True, alpha=0.3)
ax3.tick_params(axis='x', rotation=45)

# Graph 4: Distribution des prix
ax4 = axes[1, 1]
df['Prix'].plot(kind='hist', bins=30, ax=ax4, color='coral', edgecolor='black', alpha=0.7)
ax4.set_title('Distribution des Prix', fontweight='bold')
ax4.set_xlabel('Prix (€)')
ax4.set_ylabel('Fréquence')
ax4.grid(axis='y', alpha=0.3)

plt.tight_layout()
plt.show()

# Heatmap
plt.figure(figsize=(10, 6))
pivot_table = df.pivot_table(values='CA', index='Produit', columns='Region', aggfunc='sum')
sns.heatmap(pivot_table, annot=True, fmt='.0f', cmap='YlOrRd', linewidths=0.5)
plt.title('Heatmap: CA par Produit et Région', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

print("\n✨ Dashboard interactif créé avec succès par ANTON NELCON Steve!")